documentation:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md', '**/*.mdx', 'src/content/**']
ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/workflows/**']
dependencies:
  - changed-files:
      - any-glob-to-any-file: ['**/package.json', '.github/dependabot.yml']
