name: stale
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  contents: read

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: lemonfiber/spec/.github/workflows/stale.yml@ca6f4563337ae61c15af99c9b18436fd170781c1 # v1.0.51
