name: stale
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  contents: read

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: lemonfiber/spec/.github/workflows/stale.yml@d39729a2ee2b66266e3819465392abcd684f2feb # v1.0.53
